% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{section}{-1}
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{
  showspaces = false,
  showtabs = false,
  breaklines,
  commandchars=\\\{\}
}

\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={QRM II Graded Assignment (5)},
  pdfauthor={Group-20, -- Stefan Rares Ratiu, Iann Soffried, Noel Kona, Sofia Tataryn, Hashim Aburumman},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{QRM II Graded Assignment (5)}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Period 1, 2026}
\author{Group-20, -- Stefan Rares Ratiu, Iann Soffried, Noel Kona, Sofia
Tataryn, Hashim Aburumman}
\date{27-09-2026}

\begin{document}
\maketitle

\section{Introduction}\label{introduction}

This assignment is to be completed in groups of 4-5. Further, all
students in your group need to be assigned to the same R tutorial group
(Friday's tutorial). You can sign yourself up for a group on Canvas.
Please do so
\textbf{before the start of your first R tutorial on Friday September 4th.}
You can use the Discussion Board in Canvas if you do not have a group
yet or if your group is incomplete.

The assignment has 5 parts, and each part corresponds to the course
material of that week (with the exclusion of week 6, for which there is
no R programming material).

You are supposed to hand in these assignments on Canvas at the following
dates:

\begin{itemize}
\tightlist
\item
  \textbf{Deadline 1} \emph{Sunday September 27th, at 23:59pm}: you are
  supposed to hand in weeks 1, 2, and 3 of this assignment. This will
  determine 18\% of your overall course grade
\item
  \textbf{Deadline 2} \emph{Sunday October 11th, at 23:59pm}: you are
  supposed to hand in weeks 4, and 5 of this assignment. This will
  determine 12\% of your overall course grade
\end{itemize}

The R tutorials (each Friday) will consist of two halves. During the
first half, you will discuss the tutorial exercises. These can be
downloaded separately from Canvas. During the second half, you can work
on this graded assignment within your own group. The purpose is that you
find out how to work with R for doing statistical analyses by yourself.
The tutorial exercises are meant to teach you basic commands to get you
started, but to answer the problem sets in this assignment, you might
need to research your own solutions, and use functions and commands not
described in the tutorial exercises. Learning how to solve your own
research problems is integral part of learning R. When you and your
group get stuck on how to approach an exercise, the hierarchy in finding
your way is as follows:

\begin{itemize}
\tightlist
\item
  use the concepts from the tutorial exercises;
\item
  use the cheat sheets available on Canvas;
\item
  use Google, YouTube, StackOverflow, or another website;
\item
  ask the teacher.
\end{itemize}

The use of generative AI is \textbf{not} permitted and may result in a
grade of 0. See the AI protocol in the course manual for details.

To answer the assignment, you can simply fill out this R markdown
document. There are designated places which you can fill with R code.
There are also designated spaces for you to answer each question. Often,
the structure of an answer will be as follows. First, you type the R
code in the designated box. This will show how you analyzed the data to
get the answer to the question. Below the box for the R code, you will
then summarize your answer to the question, i.e.~what are the
conclusions that you draw from the data analysis?

When handing in, you are supposed to submit this .Rmd file, and a
knitted version of this document. You can knit this document to pdf,
word, or html. Knitting to pdf requires you to have a .tex distribution
installed on your computer. Knitting to Word requires you to have Word
installed.

The exercises are designed such that you should be able to finish the
majority of them during the tutorial each week. If you are not able to
finish them fully during that time, you are expected to work on it in
your own time using the computers on campus or your own device. It is
best to meet as a group in-person when working together. If you want to
work remotely, github is a good platform to guarantee smooth
collaboration. Alternatively, you can email this .Rmd file back and
forth to one another as a group, but this is not recommended as it is
more cumbersome.

We encourage you to keep your code blocks, printing statements, and
final answers, as short as possible. In any case, there is a page limit
of 6 pages per week, which encompasses the total length of this document
which consists of the questions, your coding lines, and your answers.
When your answers to questions of the respective week exceed this page
limit, they will not be graded, resulting in zero points.

Each week consists of 1, 2, or 3 subquestions. The total amount of
points you can earn per week is 20 points.

\section{Week 1}\label{week-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find the dataset ``movies4.tsv'' on Canvas. Describe your data set:
  How many observations does it have. How many variables are there? How
  many subjects? What consists of a subject? \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"movies4.tsv"}\NormalTok{, }\AttributeTok{sep =} \StringTok{"}\SpecialCharTok{\textbackslash{}t}\StringTok{"}\NormalTok{)}
\FunctionTok{dim}\NormalTok{(movies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 808  19
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{title))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 808
\end{verbatim}

\textbf{Your Answer:}

The data set has 808 observations and 19 variables, such as budget,
popularity, genre, runtime etc. There are 808 subjects and one subject
is a movie. Every title appears only once, so each row is a different
movie, and this is why the number of observations is equal to subjects.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Which of the following types of variables are present in your data
  set? (i) nominal; (ii) ordinal; (iii); interval; (iv) ratio. If
  present, name one example of such a variable present in your data set.
  \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(movies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    808 obs. of  19 variables:
##  $ index              : int  2256 2473 1514 1512 395 3156 4753 4590 1665 2714 ...
##  $ budget             : num  0.0 1.5e+07 3.2e+07 3.2e+07 8.5e+07 0.0 6.0e+04 0.0 0.0 1.4e+07 ...
##  $ keywords           : chr  NA "barcelona spain menage a trois author" "gunslinger revenge prairie shootout pistol" "robbery double life dual identity small town indiana" ...
##  $ original_language  : chr  "en" "en" "en" "en" ...
##  $ title              : chr  "The Oogieloves in the Big Balloon Adventure" "Vicky Cristina Barcelona" "The Quick and the Dead" "A History of Violence" ...
##  $ popularity         : num  0.286 32.758 16.473 34.629 44.967 ...
##  $ release_date       : chr  "2012-08-29" "2008-08-15" "1995-02-09" "2005-09-23" ...
##  $ revenue            : num  0.00 9.64e+07 1.86e+07 6.07e+07 1.94e+08 ...
##  $ runtime            : int  88 96 107 96 136 92 93 97 138 149 ...
##  $ vote_average       : num  2.2 6.7 6.3 6.9 6.7 7.1 5.1 5.6 6.7 6.1 ...
##  $ vote_count         : int  8 1020 427 832 1225 83 6 4 144 86 ...
##  $ genre              : chr  "Family" "Drama" "Action" "Drama" ...
##  $ release_year       : int  2012 2008 1995 2005 2006 2011 2012 2004 2004 2011 ...
##  $ release_month      : int  8 8 2 9 12 8 10 9 9 9 ...
##  $ release_day        : int  29 15 9 23 8 4 13 23 3 30 ...
##  $ first_actor        : chr  "Christopher Lloyd" "Scarlett Johansson" "Sharon Stone" "Viggo Mortensen" ...
##  $ first_actor_gender : chr  "male" "female" "female" "male" ...
##  $ director_first_name: chr  "Matthew" "Woody" "Sam" "David" ...
##  $ director_gender    : chr  "male" "male" "male" "male" ...
\end{verbatim}

\textbf{Your Answer:}

All four types of variables are present in the data set. The firs type
is nominal, where genre is included in this variable type. The second
type is ordinal, where vote\_average is included in this variable type.
The third is interval, where release\_year is included in this variable
type. The fourth is ratio, where budget is included in this variable
type.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  A movie studio wants to know which types of movies give maximal
  profit. Perform the following steps to provide the movie studio with
  an analysis which corresponds to their request:
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create the variable profits as the revenue of a movie minus its
  budget. Report its mean, median, maximum, and minimum.
  \textbf{[2 points]}
\item
  Which movie has the highest profits in your data set and how much are
  these profits. Which movie has the lowest and how much are its
  profits? If multiple movies have the exact same highest or lowest
  profits, give only one example. \textbf{[2 points]}
\item
  Create a boxplot of the variable profits. Make sure it has an
  appropriate title, and appropriate titles and labels for the x- and
  y-axis. Give Q1, Q2, Q3, and Q4. What does this tell you about the
  nature of making money in the movies industry? \textbf{[2 points]}
\item
  Add a new variable to your data set the log of profits. When creating
  this variable, what happens to movies for which profits is zero or
  negative? What then happens when you calculate the mean of log of
  profits? \textbf{[2 points]}
\item
  For movies that have a profit of zero or less, replace log of profits
  with ``NA''. What is now the mean of log of profits? Create a boxplot
  for log of profits, again with an appropriate title, x- and y-axis
  labels. How does it compare to the boxplot you made under c.)?
  \textbf{[2 points]}
\item
  Create a scatterplot of with the runtime of movies on the x-axis and
  the average vote of movies on the y-axis. What do you conclude from
  the scatterplot? Are movies with a longer runtime considered worse or
  better by the audience, or does the audience not have a preference?
  Why do you think this is the case? \textbf{[2 points]}
\end{enumerate}

For each step, you should provide first all the code you used to answer
the question and then formulate an answer using full sentences.

\emph{Step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{moviesprofits}\OtherTok{\textless{}{-}}\NormalTok{movies}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{{-}}\NormalTok{ movies}\SpecialCharTok{$}\NormalTok{budget}
\FunctionTok{summary}\NormalTok{(moviesprofits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
## -150000000   -1849854          0   52885669   49711134 1299557910
\end{verbatim}

\textbf{Your Answer:}

The mean profit is 52885669, which is around 52.9 million, and the
median profit is 0. The highest profit or the maximum is 1299557910,
which is around 1.3 billion, and the lowest or the minimum is
-150000000, which is a loss of 150 million. Th mean is far above the
median, so profits are right-skewed, which means that a few hits pull
the average or mean up. The median is 0 because some of the movies have
both a budget and revenue of 0, which probably means the data is
missing.

\emph{Step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movieprofits}\OtherTok{\textless{}{-}}\NormalTok{movies}\SpecialCharTok{$}\NormalTok{revenue}\SpecialCharTok{{-}}\NormalTok{movies}\SpecialCharTok{$}\NormalTok{budget}

\NormalTok{movies}\SpecialCharTok{$}\NormalTok{title[movieprofits }\SpecialCharTok{==} \FunctionTok{max}\NormalTok{(movieprofits)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "The Avengers"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{max}\NormalTok{(movieprofits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1299557910
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies}\SpecialCharTok{$}\NormalTok{title[movieprofits }\SpecialCharTok{==} \FunctionTok{min}\NormalTok{(movieprofits)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "The Wolfman"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{min}\NormalTok{(movieprofits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.5e+08
\end{verbatim}

\textbf{Your Answer:}

The movie with the highest profit is The Avengers, with 1299557910,
which is around 1.3 billion. The movie with the lowest profit is The
Wolfman, with -150000000, which is a loss of 150 million. The Wolfman
has the lowest profit because the revenue is recorded as 0 and the the
budget is 150 million, so the revenue may be missing from the data.

\emph{Step c}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies}\SpecialCharTok{$}\NormalTok{profits}\OtherTok{\textless{}{-}}\NormalTok{moviesprofits}
\FunctionTok{ggplot}\NormalTok{(movies, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ profits }\SpecialCharTok{/} \DecValTok{1000000}\NormalTok{)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Boxplot of profits for the movies"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"All movies"}\NormalTok{ , }\AttributeTok{y =} \StringTok{"Profits"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment5_files/Assignment5_files/figure-latex/unnamed-chunk-5-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{quantile}\NormalTok{(moviesprofits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         0%        25%        50%        75%       100% 
## -150000000   -1849854          0   49711134 1299557910
\end{verbatim}

\textbf{Your Answer:}

The quartiles of profits are Q1 = -1849854, Q2/median = 0, Q3 =
49711134, and Q4/maximum = 1299557910. The interpretation of the
quartiles is that more than a quarter of movies lose money, and half
make no profit at all. The box is small and sits near zero, but there
are many large outliers above it. This shows that making money in movies
is very risky and depends on a few hits.

\emph{Step d}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movieslogprofits}\OtherTok{\textless{}{-}}\FunctionTok{log}\NormalTok{(moviesprofits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in log(moviesprofits): NaNs produced
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(movieslogprofits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NaN
\end{verbatim}

\textbf{Your Answer:}

For the movies with a 0 profit it returns -Infinity, because log(0) goes
to -infinity. For the movies with negative profit it returns NaN,
because the log of a negative number does not exist. The log is defined
only for positive numbers. The mean of log of profits return NaN. So the
mean cannot be computed until these values are dealt with.

\emph{Step e}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movieslogprofits[moviesprofits }\SpecialCharTok{\textless{}=} \DecValTok{0}\NormalTok{] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
\FunctionTok{mean}\NormalTok{(movieslogprofits, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17.33131
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies}\SpecialCharTok{$}\NormalTok{log\_profits}\OtherTok{\textless{}{-}}\NormalTok{movieslogprofits}
\FunctionTok{ggplot}\NormalTok{(movies, }\FunctionTok{aes}\NormalTok{( }\AttributeTok{y =}\NormalTok{ log\_profits)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Boxplot of log of movie profits"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Movies with positive profits"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Log of profits"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 407 rows containing non-finite outside the scale range
## (`stat_boxplot()`).
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment5_files/Assignment5_files/figure-latex/unnamed-chunk-7-1.pdf}}

\textbf{Your Answer:}

After replacing the log of profits with NA for movies with negative or 0
profit, the mean log of profits is 17.33, which is calculated over the
profitable movies. If we convert the mean is about 33.6 million. This
boxplot is much more symmetric, compared with the boxplot in c). Now the
box is visible and the median is in the middle. In c) the box was near
to 0 and and there were many outilers at the top. Taking the log
compresses the very large values, so the huge movies no longer dominate
the plot. The downside of this exercise is that the movies with a loss
or 0 profit are left out, so this plot describes only movies that were
profitable.

\emph{Step f}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(movies, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ runtime, }\AttributeTok{y =}\NormalTok{ vote\_average)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Runtime vs. average vote of movies"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Runtime (minutes)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Average vote (0{-}10)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment5_files/Assignment5_files/figure-latex/unnamed-chunk-8-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{runtime,movies}\SpecialCharTok{$}\NormalTok{vote\_average)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3550796
\end{verbatim}

\textbf{Your Answer:}

The scatterplot shows a weak to moderate positive relationship between
runtime and average vote, the correlation is equal to 0.36. Most of the
movies last between 90 and 120 minutes and have a score between 5 and 7.
The trend line slopes upward, which means movies shorter than 90 minutes
score about 5.6 on average, while movies over 150 minutes score about
6.9. Longer movies tend to be rated better by the audience, although
there is a lot of spread around the line. The audience might prefer
longer movies because of the big budgets, better story and actors, while
short movies have lower budgets.

\section{Week 2}\label{week-2}

1 Is your dataset movies4.tsv the full population, or is it a sample of
a larger population? If the latter, how would you describe the full
population? \textbf{[4 points]}

\textbf{Your Answer:}

It is the sample of a larger population. This data set consists
primarily of widely distributed, mostly mainstream English-language and
major international commercial movies. The full population would
represent all commercially distributed movies throughout cinematic
history.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  For which actor in your data set do you observe the most movies?
  \textbf{[2 points]}
\item
  What is the average revenue of the movie in which this actor plays and
  does the revenue lie above or below the revenue of an average movie
  according to your data set? \textbf{[2 points]}\\
\item
  How trustworthy do you consider your conclusion to answer 2b? Use the
  term ``law of large numbers'' in your explanation. \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top\_actor\_summary }\OtherTok{\textless{}{-}}\NormalTok{ movies }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(first\_actor)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(first\_actor, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{top\_actor\_name }\OtherTok{\textless{}{-}}\NormalTok{ top\_actor\_summary}\SpecialCharTok{$}\NormalTok{first\_actor[}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

With 9 movies, Bruce Willis is the actor with the most movies in the
data set.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{avg\_bruce}\OtherTok{\textless{}{-}}\NormalTok{ movies }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(first\_actor}\SpecialCharTok{==}\StringTok{"Bruce Willis"} \SpecialCharTok{\&}\NormalTok{ revenue }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{( }\AttributeTok{avg\_rev =} \FunctionTok{mean}\NormalTok{(revenue), }\AttributeTok{na.rm=}\NormalTok{T) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pull}\NormalTok{(avg\_rev)}

\NormalTok{avg\_rev\_ovr}\OtherTok{\textless{}{-}}\FunctionTok{mean}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{revenue, }\AttributeTok{na.rm=}\NormalTok{T)}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Bruce Willis has an average revenue of \$255,7 million in his movies in
this data set, lying over the overall average of the population of
\$82,7 million.a

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bruce\_stats }\OtherTok{\textless{}{-}}\NormalTok{ movies }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(first\_actor }\SpecialCharTok{==} \StringTok{"Bruce Willis"} \SpecialCharTok{\&}\NormalTok{ revenue }\SpecialCharTok{\textgreater{}} \DecValTok{0} \SpecialCharTok{\&} \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(revenue)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{sample\_size =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{mean\_revenue =} \FunctionTok{mean}\NormalTok{(revenue),}
    \AttributeTok{sd\_revenue =} \FunctionTok{sd}\NormalTok{(revenue))}

\FunctionTok{print}\NormalTok{(bruce\_stats)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   sample_size mean_revenue sd_revenue
## 1           9    255652124  244997333
\end{verbatim}

\textbf{Your Answer:}

The conclusion is not trustworthy due to the very small sample size and
extreme variance. According to the law of large numbers, as a sample
size becomes larger, the sample mean converges closer to the true
population mean. In the filtered dataset, it is only possible to observe
a sample size of 9 movies where Bruce Willis is listed as the
``first\_actor''. Because the standard deviation (\$245 million) is
nearly as large as the sample mean (\$255 million), individual
blockbuster outliers impact the average heavily. While the sample mean
is large enough that Bruce Willis' average likely remains above the
overall dataset average (\$82.7 million), 9 is far too small for the law
of large numbers to ensure that this sample mean is an accurate estimate
of his true career population average.

3 For this question, you will assume that your data set is the full
population.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Recode profits such that it is expressed in millions. What is the
  variance of the variable profits (in millions) in your data set?
  \textbf{[2 points]}
\item
  Create a new data set, called movies\_sample. Make sure that it is a
  random sample of your data set of 25 movies. What is the variance of
  profits in this random sample? How does it compare to the variance of
  profits in 2a? \textbf{[2 points]}
\item
  In a for loop, create 100 different samples of 25 movies, as in b, and
  estimate the variance within each sample. Save the variance of each
  sample in a vector called sample\_vars. So the first position of the
  vector would have the variance of the first sample, the second
  position the variance of the second sample, etc. Print the start of
  this vector. \textbf{[2 points]}
\item
  Summarize and make a histogram of sample\_vars. What is the mean,
  standard deviation and shape of its distribution? \textbf{[2 points]}
\item
  In your opinion, is a sample of 25 movies sufficient to get a reliable
  estimate of the population variance of profits, using the sample
  variance? Explain? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies}\OtherTok{\textless{}{-}}\NormalTok{ movies }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{( }\AttributeTok{profit =}\NormalTok{ (revenue }\SpecialCharTok{{-}}\NormalTok{ budget) }\SpecialCharTok{/} \DecValTok{1000000}\NormalTok{)}

\NormalTok{pop\_var\_profit}\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{profit, }\AttributeTok{na.rm=}\NormalTok{T) }\SpecialCharTok{*}\NormalTok{ ((}\FunctionTok{nrow}\NormalTok{(movies)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(movies))}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

After recoding profits to millions, the variance of profit\_millions in
the full dataset is approximately \$20.245,47, depending on exact
dataset row counts and handling of zero values).

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{9849}\NormalTok{)}

\NormalTok{movies\_sample }\OtherTok{\textless{}{-}}\NormalTok{ movies }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(profit)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_sample}\NormalTok{(}\AttributeTok{n =} \DecValTok{25}\NormalTok{)}

\NormalTok{sample\_var\_profit }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(movies\_sample}\SpecialCharTok{$}\NormalTok{profit)}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Due to sampling variability, the variance in a single small sample of 25
movies can differ substantially from the population variance found in
3a. Depending on whether high-budget blockbusters or major box-office
flops were randomly selected into this specific sample, the sample
variance could be significantly higher or lower than the overall
population variance. In this case it was \$17.408, lower than the
population variance.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{9849}\NormalTok{)}

\NormalTok{n\_simulations }\OtherTok{\textless{}{-}} \DecValTok{100}
\NormalTok{sample\_vars }\OtherTok{\textless{}{-}} \FunctionTok{numeric}\NormalTok{(n\_simulations)}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_simulations) \{}
\NormalTok{  current\_sample }\OtherTok{\textless{}{-}}\NormalTok{ movies }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice\_sample}\NormalTok{(}\AttributeTok{n =} \DecValTok{25}\NormalTok{)}
\NormalTok{  sample\_vars[i] }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(current\_sample}\SpecialCharTok{$}\NormalTok{profit)}
\NormalTok{\}}

\FunctionTok{head}\NormalTok{(sample\_vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17408.060 55120.157 19341.454  7620.101  4789.374  7268.688
\end{verbatim}

\textbf{Your Answer:}

The first few values of sample\_vars display noticeable variation across
iterations, showing how much sample variance fluctuates from one random
sample of 25 movies to another.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean\_sample\_vars}\OtherTok{\textless{}{-}}\FunctionTok{mean}\NormalTok{(sample\_vars)}
\NormalTok{sd\_sample\_vars}\OtherTok{\textless{}{-}}\FunctionTok{sd}\NormalTok{(sample\_vars)}

\FunctionTok{hist}\NormalTok{(sample\_vars,}
     \AttributeTok{main=}\StringTok{"Distribution of Sample Variances (n=25)"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Sample Variance of Profits(millions)"}
\NormalTok{     )}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment5_files/Assignment5_files/figure-latex/unnamed-chunk-15-1.pdf}}

\textbf{Your Answer:}

Across our 100 random samples, the mean of the sample variances sits
around 19340, but the standard deviation is huge at roughly 18590.

Looking at the histogram, the distribution is heavily skewed to the
right. Most samples give a pretty modest variance, but sometimes a
sample happens to draw a couple of massive blockbusters, which spikes
that sample's variance way out to the right and creates a long tail.

\emph{step e}

\textbf{Your Answer:}

No, a sample size of 25 movies really isn't enough to get a reliable
estimate of the population variance.

First off, our results from step 3d show that the sample variances swing
wildly from one sample to the next---the standard deviation of those
variances is huge.

The main issue is how heavily right-skewed box office data is. Movies
have extreme outliers, like massive blockbusters or high-budget flops.
So even though sample variance is technically an unbiased estimator on
average, any single random sample of 25 movies is just too small to give
you a trustworthy estimate of the true population variance.

\section{Week 3}\label{week-3}

For the next part of the assignment, assume that the movies in your data
frame are a random sample of a larger population of movies.

1

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a new data set that only includes movies that are of the genre
  ``Thriller''. For these thriller movies, give a 99 percent confidence
  interval for the variable \emph{runtime}. Interpret the result.
  \textbf{[2 points]}
\item
  Now, assume that the variance of \emph{runtime} amongst thriller
  movies in your data is exactly the same as the variance of
  \emph{runtime} in the population. Under this assumption, give a 99
  percent confidence interval for the variable \emph{runtime} among
  thriller movies. Interpret the result. Is you confidence interval
  wider or less wide than the one you found under question 1a? Why is
  that the case? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{thriller}\OtherTok{\textless{}{-}}\NormalTok{movies}\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(genre}\SpecialCharTok{==}\StringTok{"Thriller"}\NormalTok{)}

\NormalTok{t1}\OtherTok{\textless{}{-}}\FunctionTok{t.test}\NormalTok{(thriller}\SpecialCharTok{$}\NormalTok{runtime,}\AttributeTok{conf.level=}\FloatTok{0.99}\NormalTok{)}

\FunctionTok{print}\NormalTok{ (t1}\SpecialCharTok{$}\NormalTok{conf.int)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 100.5517 109.8965
## attr(,"conf.level")
## [1] 0.99
\end{verbatim}

\textbf{Your Answer:}

With the sample provided, there is a 99\% confidence that the average
runtime of thriller movies lies between 100.55 and 109.9

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean\_runtime}\OtherTok{\textless{}{-}}\FunctionTok{mean}\NormalTok{(thriller}\SpecialCharTok{$}\NormalTok{runtime)}
\NormalTok{sigma}\OtherTok{\textless{}{-}}\FunctionTok{sd}\NormalTok{(thriller}\SpecialCharTok{$}\NormalTok{runtime)}
\NormalTok{n}\OtherTok{\textless{}{-}}\FunctionTok{length}\NormalTok{(thriller}\SpecialCharTok{$}\NormalTok{runtime)}

\NormalTok{z\_a2}\OtherTok{\textless{}{-}}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{)}
\NormalTok{error}\OtherTok{\textless{}{-}}\NormalTok{z\_a2}\SpecialCharTok{*}\NormalTok{sigma}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)}

\NormalTok{LOW}\OtherTok{\textless{}{-}}\NormalTok{mean\_runtime}\SpecialCharTok{{-}}\NormalTok{error}
\NormalTok{UP}\OtherTok{\textless{}{-}}\NormalTok{mean\_runtime}\SpecialCharTok{+}\NormalTok{error}

\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(LOW,UP))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 100.6292 109.8191
\end{verbatim}

\textbf{Your Answer:}

Under the given assumption, the 99\% confidence interval for the mean
runtime of thriller movies is 100.63 and 109.82 minutes. This confidence
interval is narrower than the one from question 1a since the population
variance is known. With a known population variance there is less
uncertainty when estimating, so the normal distribution is used rather
than the t distribution.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Using an appropriate five-step procedure, set up a test for the null
  hypothesis that the variance of runtime equals \(500\). Clearly state
  your null hypothesis, alternative hypothesis your test statistic, your
  critical value, and your conclusion. \textbf{[2 points]}
\item
  For the validity of your test in 2a, what assumption about the
  distribution of revenue needs to hold? Make an appropriate plot to
  test this assumption. What do you conclude? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s2}\OtherTok{\textless{}{-}}\FunctionTok{var}\NormalTok{(thriller}\SpecialCharTok{$}\NormalTok{runtime)}
\NormalTok{h0}\OtherTok{\textless{}{-}}\DecValTok{500}
\NormalTok{df}\OtherTok{\textless{}{-}}\FunctionTok{length}\NormalTok{(thriller}\SpecialCharTok{$}\NormalTok{runtime)}\SpecialCharTok{{-}}\DecValTok{1}
\NormalTok{chisq}\OtherTok{\textless{}{-}}\NormalTok{df}\SpecialCharTok{*}\NormalTok{s2}\SpecialCharTok{/}\NormalTok{h0}

\NormalTok{chi\_low}\OtherTok{\textless{}{-}}\FunctionTok{qchisq}\NormalTok{(}\FloatTok{0.025}\NormalTok{,df)}
\NormalTok{chi\_high}\OtherTok{\textless{}{-}}\FunctionTok{qchisq}\NormalTok{(}\FloatTok{0.975}\NormalTok{,df)}

\FunctionTok{print}\NormalTok{(chisq)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 84.90034
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(chi\_low,chi\_high))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  87.21279 146.57105
\end{verbatim}

\textbf{Your Answer:}

The null hypothesis is H₀: σ² = 500 The alternative hypothesis is H₁: σ²
≠ 500. The test statistic is the calculated chi-square statistic, and
the two critical values are given by the lower and upper critical
values.The null hypothesis is rejected if the test statistic lies
outside the two critical values. In this case, the test statistic is
84.9 and the two critical values are 87.21 and 146.57, so the test
statistic is outside the critical region and we reject the null
hypothesis. Therefore, given the significance level of 5\% we can infer
that there is sufficient statistical evidence to prove that the
population variance of thriller movies runtime differs from 500.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(thriller}\SpecialCharTok{$}\NormalTok{runtime,}
     \AttributeTok{main=}\StringTok{"Distribution of Thriller Runtime"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Runtime"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment5_files/Assignment5_files/figure-latex/unnamed-chunk-19-1.pdf}}

\textbf{Your Answer:}

For the validity of the chi square test for a population variance, the
assumption that needs to hold is that the variable is normally
distributed. The histogram depicts the distribution of thriller movie
runtimes. The distribution appears more or less normal, so the normality
assumption is reasonably satisfied.9

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  There is an argument going on in the movie studio. \emph{Bob} claims
  that they should make higher-quality movies, as this will bring in
  more profits. \emph{Chantal} disagrees. She tells Bob that mediocre
  movies bring in the most profits. You are asked to advise on who is
  right.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a new variable called vote\_average\_rounded. Make sure this
  variable is the same as vote\_average, but without any decimals (i.e.,
  a 6.3 becomes a 6, a 8.7 an 8, etc.). Display a histogram of
  vote\_average\_rounded. \textbf{[2 points]}
\item
  Create a scatter plot with vote\_average\_rounded on the x axis and
  the mean of profits within each category of vote\_average\_rounded on
  the y-axis. Make sure it has an appropriate title, and appropriate
  titles and labels for the x- and y-axis. At which rating of movies are
  profits the highest? \textbf{[3 points]}
\item
  Recreate the scatter plot with year on the x axis and mean\_profits on
  the y-axis, but now add bars around each point, indicating the 95\%
  confidence interval. \textbf{[3 points]}
\item
  Write an advice to settle the argument between Bob and Chantal.
  \textbf{[4 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ movies}\OtherTok{\textless{}{-}}\NormalTok{movies}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{vote\_average\_rounded=}\FunctionTok{floor}\NormalTok{(vote\_average))}

\FunctionTok{hist}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{vote\_average\_rounded,}
     \AttributeTok{main=}\StringTok{"Distribution of Rounded Movie Ratings"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Rounded Vote Average"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment5_files/Assignment5_files/figure-latex/unnamed-chunk-20-1.pdf}}

\textbf{Your Answer:}

The variable vote\_average\_rounded was created by removing the decimals
of the original vote average. The histogram depicts the distribution of
these rounded ratings.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies}\OtherTok{\textless{}{-}}\NormalTok{movies}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{profit=}\NormalTok{(revenue}\SpecialCharTok{{-}}\NormalTok{budget))}

\NormalTok{mean\_profits}\OtherTok{\textless{}{-}}\FunctionTok{tapply}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{profit,}
\NormalTok{                     movies}\SpecialCharTok{$}\NormalTok{vote\_average\_rounded,mean,}\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{print}\NormalTok{(mean\_profits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            0            2            3            4            5            6 
##        -0.25    374996.75 -15156533.38  -3283506.84  24557416.21  61782686.81 
##            7            8           10 
## 103150179.76 241184708.60        -1.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(mean\_profits,}
     \AttributeTok{main=}\StringTok{"Mean Profit by Movie Rating"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Rounded Vote Average"}\NormalTok{,}
     \AttributeTok{ylab=}\StringTok{"Mean Profit"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment5_files/Assignment5_files/figure-latex/unnamed-chunk-21-1.pdf}}

\textbf{Your Answer:}

The scatter plot illustrates how much profit a film earns in each
particular vote-average category. The most profitable category is the
one with a rating of 8. Thus, based on the given data regarding films,
the movies with this rating have the maximum average profit earned.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean\_profits}\OtherTok{\textless{}{-}}\FunctionTok{tapply}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{profit,}
\NormalTok{                     movies}\SpecialCharTok{$}\NormalTok{release\_year,}
\NormalTok{                     mean,}
                     \AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{years}\OtherTok{\textless{}{-}}\FunctionTok{sort}\NormalTok{(}\FunctionTok{unique}\NormalTok{(movies}\SpecialCharTok{$}\NormalTok{release\_year))}

\NormalTok{lower}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{()}
\NormalTok{upper}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(years))\{}
\NormalTok{  profits}\OtherTok{\textless{}{-}}\NormalTok{movies}\SpecialCharTok{$}\NormalTok{profit[movies}\SpecialCharTok{$}\NormalTok{release\_year}\SpecialCharTok{==}\NormalTok{years[i]]}
\NormalTok{  profits}\OtherTok{\textless{}{-}}\NormalTok{profits[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(profits)]}
\NormalTok{  t1}\OtherTok{\textless{}{-}}\FunctionTok{t.test}\NormalTok{(profits)}
\NormalTok{  lower[i]}\OtherTok{\textless{}{-}}\NormalTok{t1}\SpecialCharTok{$}\NormalTok{conf.int[}\DecValTok{1}\NormalTok{]}
\NormalTok{  upper[i]}\OtherTok{\textless{}{-}}\NormalTok{t1}\SpecialCharTok{$}\NormalTok{conf.int[}\DecValTok{2}\NormalTok{]}
\NormalTok{\}}

\FunctionTok{plot}\NormalTok{(years,}
\NormalTok{     mean\_profits,}
     \AttributeTok{main=}\StringTok{"Mean Movie Profit by Year"}\NormalTok{,}
     \AttributeTok{xlab=}\StringTok{"Release Year"}\NormalTok{,}
     \AttributeTok{ylab=}\StringTok{"Mean Profit"}\NormalTok{)}

\FunctionTok{arrows}\NormalTok{(years,lower,}
\NormalTok{       years,upper,}
       \AttributeTok{angle=}\DecValTok{90}\NormalTok{,}
       \AttributeTok{code=}\DecValTok{3}\NormalTok{,}
       \AttributeTok{length=}\FloatTok{0.05}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment5_files/Assignment5_files/figure-latex/unnamed-chunk-22-1.pdf}}

\textbf{Your Answer:}

The chart depicts the average earnings of films for each year in the
records while also showing the 95\% confidence intervals. The dots
indicate the calculated average earnings of films for each year, and the
spikes reflect the uncertainty regarding those calculations. The width
of the confidence intervals differs from year to year due to different
quantities of films and their variability in different years.

\emph{step d}

\textbf{Your Answer:}

The data suggests that average earnings change depending on the movie
rating, where one category has the highest average earnings. However,
this does not imply that movie quality influences the earnings since the
relationship observed could be confounded by other factors like budget,
popularity, type, actors, or the year of release. Thus, the results of
this study can hardly indicate whether high-quality films or ones of
mediocre quality earn the most. It is advisable for the company to
consider the uncertainty in calculations and other factors before making
conclusions.

\section{Week 4}\label{week-4}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  There is another argument going on in the movie studio. \emph{Bob}
  claims that production budgets are getting out of hand, and that the
  studio should focus on making cheaper movies. \emph{Chantal}
  disagrees. She tells Bob that ``Every dollar we spend on movie
  production is more than offset by the increase in movie profits'\,'.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Set up a regression model to test Chantal's claim, and estimate it.
  That is, estimate:
  \[\text{Profits}_i=\beta_0+\beta_1 \text{Budget}_i +\varepsilon_i.\]
  Print a summary of your estimated model. \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) and how do you interpet it?
  \textbf{[2 points]}
\item
  Test for the null hypothesis that \(\beta_1 \geq 0\). Report the
  p-value and state your conclusion. \textbf{[2 points]}
\item
  Next, estimate the model
  \[\text{Log Profits}_i=\beta_0+\beta_1 \text{Log Budget}_i +\varepsilon_i.\]
  When creating the variables Log Profits and Log Budget, make sure that
  movies with a Revenue or Budget of zero are assigned the value ``NA''.
  Print a summary of your estimated model \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) and how do you interpet it?
  \textbf{[2 points]}
\item
  Which model has better fit? The level-level model or the log-log
  model? Explain. \textbf{[2 points]}
\item
  Who do you think is correct? Bob or Chantal? What would you advise the
  movie studio to do? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step g}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Make a plot with a 95\% confidence interval with the mean log of
  budget on the y-axis, and whether the first actor of the movie is male
  or female on the x-axis. What do you conclude? \textbf{[2 points]}
\item
  Estimate the following simple OLS model:
  \(log(budget)_i=\beta_0+\beta_1 \text(FirstActorMale)_i + \varepsilon_i.\)
  Is the estimated coefficient for \(\beta_1\) significantly different
  from zero? How do you interpret its estimate, and how does this relate
  to your conclusion in 2a? \textbf{[2 points]}
\item
  Now, have a close look at your data frame. Can you find any instances
  of male first actors who are wrongly labeled as being female, or vice
  versa? What would such mislabelling mean for the coefficient you
  estimated under 2b? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\section{Week 5}\label{week-5}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\item
  Create a plot of the mean profits by month of release. Do you see any
  indication that month of release matters to the profits of the movie?
  \textbf{[2 points]}
\item
  Estimate an OLS model which has as dependent variable the log of
  profits of a movie, and as independent variable the log of budget, a
  dummy for whether the movie was released in english or not, and a
  linear term for the month of release. Show a summary of the resulting
  model and interpret each coefficient. \textbf{[4 points]}
\item
  Test for the hypothesis that the coefficient that belongs to month of
  release is zero. \textbf{[2 points]}
\item
  Based on your plot in a.) do you consider the choice that month of
  release enters the model linearly under b.) reasonable? Estimate a
  specification that allows for a more flexible curve. In this new
  specification, test for the null hypothesis that month of release does
  not impact profits. This might require testing multiple terms at once.
  \textbf{[4 points]}
\item
  One executive at the studio wants to time the release of the movie to
  a specific month of the year such that they can maximize revenue.
  Based on your model under d.), What would you advise the movie studio
  regarding the timing of the release of the movie? \textbf{[2 points]}
\end{enumerate}

The movie studio that you work at is releasing a new movie in 2026. It
will be an English-spoken Thriller movie with a budget of 40,000,0000.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Estimate a model that is able to predict the revenue of this movie.
  Give its predicted revenue and include a 99\% prediction interval.
  \textbf{[6 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}


\end{document}
